# Generated by Django 6.0.6 on 2026-06-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('logo', models.ImageField(default='default.png', upload_to='')),
                ('comptes', models.ManyToManyField(blank=True, related_name='compagnies', to='compte.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.compagnie')),
            ],
        ),
        migrations.CreateModel(
            name='DetailFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.compte')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='facture.facture')),
            ],
        ),
    ]
