# Generated by Django 6.0.6 on 2026-07-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('logo', models.CharField(default='images.png', help_text='Nom du fichier logo dans static/images/logos (ex: images.png).', max_length=100)),
                ('cap_ou_car', models.CharField(blank=True, choices=[('CAP', 'CAP'), ('CAR', 'CAR'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10, null=True)),
                ('comptes', models.ManyToManyField(blank=True, related_name='compagnies', to='compte.compte')),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieSoldeDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compagnie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_depart', to='facture.compagnie')),
            ],
            options={
                'verbose_name': 'Solde de depart compagnie',
                'verbose_name_plural': 'Soldes de depart compagnies',
                'ordering': ['compagnie__nom'],
            },
        ),
        migrations.CreateModel(
            name='CompteReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_compte', models.CharField(max_length=60)),
                ('type_compte', models.CharField(blank=True, max_length=20)),
                ('nom_affichage', models.CharField(blank=True, max_length=60)),
                ('type_onglet', models.CharField(choices=[('banque', 'Banque'), ('carte_credit', 'Carte de crédit'), ('marge_credit', 'Marge de crédit'), ('autre', 'Autre')], default='banque', max_length=20)),
                ('nom_institut', models.CharField(blank=True, max_length=60)),
                ('compte_comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_releves', to='compte.compte')),
            ],
            options={
                'unique_together': {('no_compte', 'type_compte')},
            },
        ),
        migrations.CreateModel(
            name='RapportTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('transmis_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-annee', '-mois', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='rapport_taxes_mois_entre_1_et_12'), models.UniqueConstraint(fields=('annee', 'mois'), name='rapport_taxes_unique_annee_mois')],
            },
        ),
        migrations.CreateModel(
            name='Tr_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ej', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('desc_ctb', models.CharField(blank=True, max_length=40, null=True)),
                ('note_de_credit', models.BooleanField(default=False)),
                ('compagnie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_desc', to='facture.compagnie')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_desc', to='facture.source')),
            ],
        ),
        migrations.CreateModel(
            name='Releve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_source', models.CharField(max_length=200)),
                ('nom_institut', models.CharField(max_length=60)),
                ('no_compte', models.CharField(max_length=60)),
                ('type_compte', models.CharField(blank=True, default='', max_length=10)),
                ('date', models.DateField()),
                ('no_ligne', models.CharField(max_length=30)),
                ('desc_releve', models.CharField(max_length=255)),
                ('desc_ctb', models.CharField(blank=True, default='', max_length=40)),
                ('frais', models.CharField(blank=True, default='', max_length=20)),
                ('retrait', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('champ1', models.CharField(blank=True, max_length=10, null=True)),
                ('champ2', models.CharField(blank=True, max_length=10, null=True)),
                ('champ3', models.CharField(blank=True, max_length=10, null=True)),
                ('champ4', models.CharField(blank=True, max_length=10, null=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ecriture_creee', models.BooleanField(default=False)),
                ('compte_releve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves', to='facture.comptereleve')),
                ('ecriture_tr_desc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_sources', to='facture.tr_desc')),
            ],
        ),
        migrations.CreateModel(
            name='Tr_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.compte')),
                ('rapport_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_taxes', to='facture.rapporttaxes')),
                ('tr_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='facture.tr_desc')),
            ],
        ),
        migrations.AddIndex(
            model_name='tr_desc',
            index=models.Index(fields=['date', 'id'], name='facture_trdesc_date_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tr_detail',
            index=models.Index(fields=['compte', 'tr_desc', 'id'], name='facture_trd_compte_trd_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tr_detail',
            index=models.Index(fields=['tr_desc', 'id'], name='facture_trd_trd_id_idx'),
        ),
    ]
