# Generated by Django 6.0.6 on 2026-06-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='logo',
            field=models.CharField(default='images/logos/images.png', help_text='Chemin relatif dans static/ vers le logo (ex: images/logos/Hydro-Québec-Logo.png).', max_length=100),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('logo', models.ImageField(default='images.png', upload_to='')),
                ('adresse', models.CharField(max_length=60)),
                ('ville', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=60)),
                ('pays', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('compte_fr_retard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_fr_retard', to='compte.compte')),
                ('compte_tps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_tps', to='compte.compte')),
                ('compte_tvq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_tvq', to='compte.compte')),
            ],
        ),
    ]
