# Generated by Django 6.0.6 on 2026-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_alter_compagnie_logo_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.CharField(
                default='images/logos/images.png',
                help_text='Chemin relatif dans static/ vers le logo (ex: images/logos/votre-logo.png).',
                max_length=100,
            ),
        ),
    ]
