# Generated by Django 6.0.6 on 2026-07-18 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_setting_compte_vacances'),
        ('facture', '0003_tr_desc_desc_releve'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeFin',
            fields=[
                ('compte', models.OneToOneField(db_column='compte_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='compte.compte')),
                ('compte_numero', models.CharField(max_length=20)),
                ('solde_depart', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_transactions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_final', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'solde_fin',
                'ordering': ['compte_numero'],
                'managed': False,
            },
        ),
    ]
