# Generated by Django 6.0.6 on 2026-07-18 18:36

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_tr_desc_desc_releve'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    CREATE OR REPLACE VIEW solde_fin AS
                    SELECT 
                        c.id AS compte_id,
                        c.numero AS compte_numero,
                        COALESCE(s.solde_depart, 0) AS solde_depart,
                        COALESCE((
                            SELECT SUM(t.montant)
                            FROM tr_detail t
                            WHERE t.compte_id = c.id
                        ), 0) AS total_transactions,
                        COALESCE(s.solde_depart, 0) +
                        COALESCE((
                            SELECT SUM(t.montant)
                            FROM tr_detail t
                            WHERE t.compte_id = c.id
                        ), 0) AS solde_final
                    FROM compte c
                    LEFT JOIN solde_aux_livres s
                        ON s.compte_id = c.id
                    ORDER BY c.numero;
                    """,
                    reverse_sql="DROP VIEW IF EXISTS solde_fin;",
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name='SoldeFin',
                    fields=[
                        ('compte', models.OneToOneField(db_column='compte_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='compte.compte')),
                        ('compte_numero', models.CharField(max_length=20)),
                        ('solde_depart', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('total_transactions', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('solde_final', models.DecimalField(decimal_places=2, max_digits=10)),
                    ],
                    options={
                        'db_table': 'solde_fin',
                        'ordering': ['compte_numero'],
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
