# Generated by Django 6.0.6 on 2026-07-18 18:36

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW solde_fin AS
            SELECT 
                c.id AS compte_id,
                c.numero AS compte_numero,
                COALESCE(s.solde_depart, 0) AS solde_depart,
                COALESCE((
                    SELECT SUM(t.montant)
                    FROM tr_detail t
                    WHERE t.compte_id = c.id
                ), 0) AS total_transactions,
                COALESCE(s.solde_depart, 0) +
                COALESCE((
                    SELECT SUM(t.montant)
                    FROM tr_detail t
                    WHERE t.compte_id = c.id
                ), 0) AS solde_final
            FROM compte c
            LEFT JOIN solde_aux_livres s
                ON s.compte_id = c.id
            ORDER BY c.numero;
            """,
            reverse_sql="DROP VIEW IF EXISTS solde_fin;"
        )
    ]
