# Generated by Django 5.2.4 on 2026-06-23 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
        ('facture', '0003_alter_setting_logo_static_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='cap_ou_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures_cap_ou_car', to='compte.compte'),
        ),
    ]
