# Generated by Django 5.2.4 on 2026-06-23 01:27

import django.db.models.deletion
from django.db import migrations, models


def forward_copy_cap_ou_car(apps, schema_editor):
    Facture = apps.get_model('facture', 'Facture')
    Compagnie = apps.get_model('facture', 'Compagnie')

    latest_by_company = {}
    factures = (
        Facture.objects
        .select_related('compagnie')
        .filter(cap_ou_car__isnull=False)
        .order_by('compagnie_id', '-date', '-id')
    )

    for facture in factures:
        if facture.compagnie_id not in latest_by_company:
            latest_by_company[facture.compagnie_id] = facture.cap_ou_car_id

    for compagnie_id, cap_ou_car_id in latest_by_company.items():
        Compagnie.objects.filter(pk=compagnie_id).update(cap_ou_car_id=cap_ou_car_id)


def reverse_copy_cap_ou_car(apps, schema_editor):
    Facture = apps.get_model('facture', 'Facture')
    Compagnie = apps.get_model('facture', 'Compagnie')

    for compagnie in Compagnie.objects.exclude(cap_ou_car__isnull=True):
        Facture.objects.filter(compagnie_id=compagnie.pk).update(cap_ou_car_id=compagnie.cap_ou_car_id)


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
        ('facture', '0004_facture_cap_ou_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='cap_ou_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compagnies_cap_ou_car', to='compte.compte'),
        ),
        migrations.RunPython(forward_copy_cap_ou_car, reverse_copy_cap_ou_car),
        migrations.RemoveField(
            model_name='facture',
            name='cap_ou_car',
        ),
    ]
