# Generated by Django 6.0.7 on 2026-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_factures'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='soldefin',
            table='"public"."solde_fin"',
        ),
    ]
