# Generated by Django 6.0.7 on 2026-07-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_compagnie_active_alter_soldefin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptereleve',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
