# Generated by Django 6.0.6 on 2026-06-26 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0009_rapporttaxes_mensuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_compte', models.CharField(max_length=60, unique=True)),
                ('nom_affichage', models.CharField(blank=True, max_length=60)),
                ('type_onglet', models.CharField(choices=[('banque', 'Banque'), ('carte_credit', 'Carte de crédit'), ('marge_credit', 'Marge de crédit'), ('autre', 'Autre')], default='banque', max_length=20)),
                ('nom_institut', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rapporttaxes',
            options={'ordering': ['-annee', '-mois', '-id']},
        ),
        migrations.AlterField(
            model_name='releve',
            name='no_compte',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='releve',
            name='type_compte',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='releve',
            name='compte_releve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves', to='facture.comptereleve'),
        ),
    ]
