# Generated by Django 6.0.6 on 2026-06-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0010_comptereleve_alter_rapporttaxes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptereleve',
            name='type_compte',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='comptereleve',
            name='no_compte',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='comptereleve',
            unique_together={('no_compte', 'type_compte')},
        ),
    ]
