# Generated by Django 6.0.6 on 2026-08-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0010_compagnie_created_by_non_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='releve',
            name='no_cheque',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
