# Generated by Django 6.0.7 on 2026-08-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0011_releve_no_cheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cheque', models.CharField(max_length=20)),
                ('date_emission', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='facture.compagnie')),
                ('releve_ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_associe', to='facture.releve')),
                ('tr_desc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='facture.tr_desc')),
            ],
        ),
    ]
