# Generated by Django 6.0.6 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releve',
            name='ecriture_creee',
            field=models.BooleanField(default=False),
        ),
    ]
