# Generated by Django 6.0.7 on 2026-08-17 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0012_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='annule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='compagnie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='facture.compagnie'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='tr_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='facture.tr_desc'),
        ),
    ]
