# Generated by Django 6.0.7 on 2026-08-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_setting_no_cheque_depart'),
        ('facture', '0013_cheque_annule_alter_cheque_compagnie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('logo', models.CharField(default='images.png', help_text='Nom du fichier logo dans static/images/logos (ex: images.png).', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_by_non_expert', models.BooleanField(default=False)),
                ('comptes', models.ManyToManyField(blank=True, related_name='clients', to='compte.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('logo', models.CharField(default='images.png', help_text='Nom du fichier logo dans static/images/logos (ex: images.png).', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_by_non_expert', models.BooleanField(default=False)),
                ('comptes', models.ManyToManyField(blank=True, related_name='fournisseurs', to='compte.compte')),
            ],
        ),
    ]
