# Generated by Django 6.0.6 on 2026-06-27 16:05

import django.db.models.deletion
from django.db import migrations, models
from django.db.utils import OperationalError, ProgrammingError


def clear_orphan_green_flags(apps, schema_editor):
    try:
        Releve = apps.get_model('facture', 'Releve')
        Releve.objects.filter(
            ecriture_creee=True,
            ecriture_tr_desc__isnull=True,
        ).update(ecriture_creee=False)
    except (OperationalError, ProgrammingError):
        # Certaines bases clientes neuves peuvent ne pas contenir la table historique.
        return


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0013_releve_ecriture_creee'),
    ]

    operations = [
        migrations.AddField(
            model_name='releve',
            name='ecriture_tr_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_sources', to='facture.tr_desc'),
        ),
        migrations.RunPython(clear_orphan_green_flags, migrations.RunPython.noop),
    ]
