# Generated by Django 6.0.7 on 2026-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0014_client_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='afficher_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='afficher_card',
            field=models.BooleanField(default=True),
        ),
    ]
