# Generated by Django 6.0.6 on 2026-06-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0014_releve_ecriture_tr_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compagnie',
            old_name='cap_ou_car',
            new_name='cpt_associe',
        ),
    ]
