# Generated by Django 6.0.7 on 2026-08-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0015_client_afficher_card_fournisseur_afficher_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr_desc',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_desc', to='facture.client'),
        ),
        migrations.AddField(
            model_name='tr_desc',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_desc', to='facture.fournisseur'),
        ),
    ]
