# Generated by Django 6.0.6 on 2026-06-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
        ('facture', '0015_rename_cap_ou_car_compagnie_cpt_associe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='cpt_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compagnies_associees', to='compte.compte'),
        ),
    ]
