# Generated by Django 6.0.7 on 2026-08-18 20:44

import django.db.models.deletion
from django.db import migrations, models


def create_client_fournisseur_from_compagnie(apps, schema_editor):
    Compagnie = apps.get_model('facture', 'Compagnie')
    Client = apps.get_model('facture', 'Client')
    Fournisseur = apps.get_model('facture', 'Fournisseur')
    db_alias = schema_editor.connection.alias

    for compagnie in Compagnie.objects.using(db_alias).all():
        mode = (compagnie.cap_ou_car or '').strip().upper()

        if mode == 'CAP':
            fournisseur, created = Fournisseur.objects.using(db_alias).get_or_create(
                nom=compagnie.nom,
                defaults={
                    'logo': compagnie.logo,
                    'active': compagnie.active,
                    'created_by_non_expert': compagnie.created_by_non_expert,
                },
            )

        elif mode == 'CAR':
            client, created = Client.objects.using(db_alias).get_or_create(
                nom=compagnie.nom,
                defaults={
                    'logo': compagnie.logo,
                    'active': compagnie.active,
                    'created_by_non_expert': compagnie.created_by_non_expert,
                },
            )


def migrate_cheque_compagnie_data(apps, schema_editor):
    Cheque = apps.get_model('facture', 'Cheque')
    Client = apps.get_model('facture', 'Client')
    Fournisseur = apps.get_model('facture', 'Fournisseur')
    db_alias = schema_editor.connection.alias

    for cheque in Cheque.objects.using(db_alias).select_related('compagnie').filter(compagnie__isnull=False):
        mode = (cheque.compagnie.cap_ou_car or '').strip().upper()

        if mode == 'CAP':
            fournisseur = Fournisseur.objects.using(db_alias).filter(nom=cheque.compagnie.nom).first()
            if fournisseur:
                cheque.fournisseur = fournisseur
                cheque.save(using=db_alias, update_fields=['fournisseur'])

        elif mode == 'CAR':
            client = Client.objects.using(db_alias).filter(nom=cheque.compagnie.nom).first()
            if client:
                cheque.client = client
                cheque.save(using=db_alias, update_fields=['client'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0016_tr_desc_client_tr_desc_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='facture.client'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='facture.fournisseur'),
        ),
        migrations.RunPython(create_client_fournisseur_from_compagnie, reverse_noop),
        migrations.RunPython(migrate_cheque_compagnie_data, reverse_noop),
        migrations.RemoveField(
            model_name='cheque',
            name='compagnie',
        ),
    ]