# Generated by Django 6.0.6 on 2026-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0016_remove_releve_ecriture_creee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compagnie',
            name='cpt_associe',
        ),
        migrations.AddField(
            model_name='compagnie',
            name='cap_ou_car',
            field=models.CharField(blank=True, choices=[('CAP', 'CAP'), ('CAR', 'CAR'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10, null=True),
        ),
    ]
