# Generated by Django 6.0.6 on 2026-06-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
        ('facture', '0017_remove_compagnie_cpt_associe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptereleve',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_releves', to='compte.compte'),
        ),
    ]
