# Generated by Django 6.0.7 on 2026-08-19 19:27

import django.db.models.deletion
from django.db import migrations, models


def migrate_soldedepart_compagnie_data(apps, schema_editor):
    CompagnieSoldeDepart = apps.get_model('facture', 'CompagnieSoldeDepart')
    Client = apps.get_model('facture', 'Client')
    Fournisseur = apps.get_model('facture', 'Fournisseur')
    db_alias = schema_editor.connection.alias

    for solde in CompagnieSoldeDepart.objects.using(db_alias).select_related('compagnie').filter(compagnie__isnull=False):
        mode = (solde.compagnie.cap_ou_car or '').strip().upper()

        if mode == 'CAP':
            fournisseur = Fournisseur.objects.using(db_alias).filter(nom=solde.compagnie.nom).first()
            if fournisseur:
                solde.fournisseur = fournisseur
                solde.save(using=db_alias, update_fields=['fournisseur'])

        elif mode == 'CAR':
            client = Client.objects.using(db_alias).filter(nom=solde.compagnie.nom).first()
            if client:
                solde.client = client
                solde.save(using=db_alias, update_fields=['client'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0017_remove_cheque_compagnie_cheque_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compagniesoldedepart',
            options={'verbose_name': 'Solde de depart compagnie', 'verbose_name_plural': 'Soldes de depart compagnies'},
        ),
        migrations.AddField(
            model_name='compagniesoldedepart',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solde_depart', to='facture.client'),
        ),
        migrations.AddField(
            model_name='compagniesoldedepart',
            name='fournisseur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solde_depart', to='facture.fournisseur'),
        ),
        migrations.RunPython(migrate_soldedepart_compagnie_data, reverse_noop),
        migrations.RemoveField(
            model_name='compagniesoldedepart',
            name='compagnie',
        ),
    ]