# Generated by Django 6.0.6 on 2026-06-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0018_comptereleve_compte_comptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tr_desc',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
