# Generated by Django 6.0.6 on 2026-06-28 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0019_alter_tr_desc_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompagnieSoldeDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compagnie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_depart', to='facture.compagnie')),
            ],
            options={
                'verbose_name': 'Solde de depart compagnie',
                'verbose_name_plural': 'Soldes de depart compagnies',
                'ordering': ['compagnie__nom'],
            },
        ),
    ]
