# Generated by Django 6.0.6 on 2026-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_alter_compte_libelle_alter_total_desc'),
        ('facture', '0020_compagniesoldedepart'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tr_detail',
            index=models.Index(fields=['compte', 'tr_desc', 'id'], name='facture_trd_compte_trd_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tr_detail',
            index=models.Index(fields=['tr_desc', 'id'], name='facture_trd_trd_id_idx'),
        ),
    ]
