# Generated by Django 6.0.7 on 2026-08-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0020_remove_tr_desc_compagnie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compagnie',
        ),
    ]
