# Generated by Django 6.0.6 on 2026-09-14 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0032_facturephotoenattente'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturephotoenattente',
            name='tr_desc',
            field=models.ForeignKey(blank=True, help_text='Ecriture comptable creee a partir de cette photo, une fois traitee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_facture', to='facture.tr_desc'),
        ),
        migrations.AddField(
            model_name='facturephotoenattente',
            name='traite',
            field=models.BooleanField(default=False, help_text="Vrai une fois l'ecriture comptable creee. La photo est conservee (compressee) pour consultation future."),
        ),
    ]
