"""
Django settings for lecarnet project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4yu1pvs&-g1oz$+skhpve!8*+45_efkzq752#!u15h+nj^&kp='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['lecarnet.io', 'www.lecarnet.io', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'facture',
    'compte',
    'paie',
    'tenancy',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenancy.middleware.ActiveClientMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lecarnet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tenancy.context_processors.active_client',
                'facture.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'lecarnet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _env(name, default=''):
    return os.environ.get(name, default).strip()


def _load_oneclick_config():
    config_path = BASE_DIR / 'scripts' / 'oneclick.config.json'
    if not config_path.exists():
        return {}
    try:
        with config_path.open('r', encoding='utf-8') as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


_oneclick_config = _load_oneclick_config()
_oneclick_default_db = _oneclick_config.get('defaultDb', {}) if isinstance(_oneclick_config, dict) else {}
_oneclick_tenants = _oneclick_config.get('tenants', {}) if isinstance(_oneclick_config, dict) else {}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _env('DEFAULT_DB_NAME', _oneclick_default_db.get('name', 'lecarnet_central')),
        'USER': _env('DEFAULT_DB_USER', _oneclick_default_db.get('user', 'postgres')),
        'PASSWORD': _env('DEFAULT_DB_PASSWORD', _oneclick_default_db.get('password', '')),
        'HOST': _env('DEFAULT_DB_HOST', _oneclick_default_db.get('host', '127.0.0.1')),
        'PORT': _env('DEFAULT_DB_PORT', _oneclick_default_db.get('port', '5432')),
    }
}


tenant_databases_json = _env('TENANT_DATABASES_JSON', '')
if tenant_databases_json:
    tenant_databases = json.loads(tenant_databases_json)
    DATABASES.update(tenant_databases)
elif isinstance(_oneclick_tenants, dict) and _oneclick_tenants:
    DATABASES.update(_oneclick_tenants)


DATABASE_ROUTERS = [
    'tenancy.db_router.TenantDatabaseRouter',
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-CA'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'accueil'
LOGOUT_REDIRECT_URL = 'login'

AUTHENTICATION_BACKENDS = [
    'tenancy.auth_backends.CaseInsensitiveUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]
