# Generated by Django 6.0.7 on 2026-07-27 16:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencePaie',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('HEBDO', 'Hebdomadaire'), ('BIHEBDO', 'Aux 2 semaines'), ('2MOIS', '2 fois par mois'), ('MOIS', 'Par mois')], max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_periodes_par_annee', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Fréquence de paie',
                'verbose_name_plural': 'Fréquences de paie',
            },
        ),
        migrations.CreateModel(
            name='ParametresTauxPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrq_date_debut_effet', models.DateField()),
                ('rrq_date_fin_effet', models.DateField(blank=True, null=True)),
                ('taux_rrq_employe', models.DecimalField(decimal_places=5, max_digits=7)),
                ('taux_rrq_supplementaire_2_employe', models.DecimalField(decimal_places=5, default=Decimal('4.00000'), max_digits=7)),
                ('taux_rrq_employeur', models.DecimalField(decimal_places=5, max_digits=7)),
                ('exemption_base_rrq', models.DecimalField(decimal_places=2, default=Decimal('3500.00'), max_digits=12)),
                ('max_assurable_rrq', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_supplementaire_rrq', models.DecimalField(decimal_places=2, default=Decimal('85000.00'), max_digits=12)),
                ('rqap_date_debut_effet', models.DateField()),
                ('rqap_date_fin_effet', models.DateField(blank=True, null=True)),
                ('taux_rqap_employe', models.DecimalField(decimal_places=5, max_digits=7)),
                ('taux_rqap_employeur', models.DecimalField(decimal_places=5, max_digits=7)),
                ('max_assurable_rqap', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ae_date_debut_effet', models.DateField()),
                ('ae_date_fin_effet', models.DateField(blank=True, null=True)),
                ('taux_ae_employe', models.DecimalField(decimal_places=5, max_digits=7)),
                ('taux_ae_employeur', models.DecimalField(decimal_places=5, max_digits=7)),
                ('taux_cnt_employeur', models.DecimalField(decimal_places=5, default=Decimal('0.06000'), max_digits=7)),
                ('max_assurable_ae', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit_personnel_federal_min', models.DecimalField(decimal_places=2, default=Decimal('16452.00'), max_digits=12)),
                ('taux_credit_federal', models.DecimalField(decimal_places=5, default=Decimal('14.00000'), max_digits=7)),
                ('montant_canadien_pour_emploi', models.DecimalField(decimal_places=2, default=Decimal('1501.00'), max_digits=12)),
                ('abattement_federal_quebec', models.DecimalField(decimal_places=5, default=Decimal('16.50000'), max_digits=7)),
                ('seuil_federal_1', models.DecimalField(decimal_places=2, default=Decimal('58523.00'), max_digits=12)),
                ('seuil_federal_2', models.DecimalField(decimal_places=2, default=Decimal('117045.00'), max_digits=12)),
                ('seuil_federal_3', models.DecimalField(decimal_places=2, default=Decimal('181440.00'), max_digits=12)),
                ('seuil_federal_4', models.DecimalField(decimal_places=2, default=Decimal('258482.00'), max_digits=12)),
                ('taux_federal_1', models.DecimalField(decimal_places=5, default=Decimal('14.00000'), max_digits=7)),
                ('taux_federal_2', models.DecimalField(decimal_places=5, default=Decimal('20.50000'), max_digits=7)),
                ('taux_federal_3', models.DecimalField(decimal_places=5, default=Decimal('26.00000'), max_digits=7)),
                ('taux_federal_4', models.DecimalField(decimal_places=5, default=Decimal('29.00000'), max_digits=7)),
                ('taux_federal_5', models.DecimalField(decimal_places=5, default=Decimal('33.00000'), max_digits=7)),
                ('credit_personnel_quebec_min', models.DecimalField(decimal_places=2, default=Decimal('18952.00'), max_digits=12)),
                ('deduction_travailleur_qc_max_annuelle', models.DecimalField(decimal_places=2, default=Decimal('1450.00'), max_digits=12)),
                ('seuil_qc_1', models.DecimalField(decimal_places=2, default=Decimal('54345.00'), max_digits=12)),
                ('seuil_qc_2', models.DecimalField(decimal_places=2, default=Decimal('108680.00'), max_digits=12)),
                ('seuil_qc_3', models.DecimalField(decimal_places=2, default=Decimal('132245.00'), max_digits=12)),
                ('taux_qc_1', models.DecimalField(decimal_places=5, default=Decimal('14.00000'), max_digits=7)),
                ('taux_qc_2', models.DecimalField(decimal_places=5, default=Decimal('19.00000'), max_digits=7)),
                ('taux_qc_3', models.DecimalField(decimal_places=5, default=Decimal('24.00000'), max_digits=7)),
                ('taux_qc_4', models.DecimalField(decimal_places=5, default=Decimal('25.75000'), max_digits=7)),
                ('taux_credit_quebec', models.DecimalField(decimal_places=5, default=Decimal('14.00000'), max_digits=7)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parametres de taux de paie',
                'verbose_name_plural': 'Parametres de taux de paie',
                'ordering': ['-rrq_date_debut_effet', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_embauche', models.DateField()),
                ('salH', models.CharField(blank=True, max_length=40, null=True)),
                ('e_prov', models.IntegerField(blank=True, null=True)),
                ('e_fed', models.CharField(blank=True, max_length=40, null=True)),
                ('taux_vacances', models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00000'), max_digits=7, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('frequence_paie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='paie.frequencepaie')),
            ],
            options={
                'ordering': ['nom', 'prenom', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField()),
                ('date_paie', models.DateField(blank=True, null=True)),
                ('fermee', models.BooleanField(default=False)),
                ('frequence_paie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodes', to='paie.frequencepaie')),
            ],
            options={
                'ordering': ['-date_fin', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('vacances_payees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vacances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_personnel_federal_td1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_personnel_quebec_tp1015', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_code_f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_tp1015_j', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_tp1016_j1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retenue_supplementaire_qc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotisation_supplementaire_rrq_csa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_brut_periode', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rqap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rrq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ae', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('impot_federal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('impot_provincial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_retenues', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paies', to='paie.employe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paies', to='paie.periodepaie')),
            ],
            options={
                'ordering': ['-periode__date_fin', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['date_embauche', 'id'], name='paie_employe_date_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodepaie',
            constraint=models.UniqueConstraint(fields=('frequence_paie', 'date_debut', 'date_fin'), name='paie_periode_unique_frequence_dates'),
        ),
        migrations.AddConstraint(
            model_name='paie',
            constraint=models.UniqueConstraint(fields=('employe', 'periode'), name='paie_unique_employe_periode'),
        ),
    ]
