# Generated by Django 6.0.6 on 2026-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencePaie',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('HEBDO', 'Hebdomadaire'), ('BIHEBDO', 'Aux 2 semaines'), ('2MOIS', '2 fois par mois'), ('MOIS', 'Par mois')], max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_periodes_par_annee', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Fréquence de paie',
                'verbose_name_plural': 'Fréquences de paie',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_embauche', models.DateField()),
                ('salH', models.CharField(blank=True, max_length=40, null=True)),
                ('e_prov', models.IntegerField(blank=True, null=True)),
                ('e_fed', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date_embauche', 'id'], name='paie_employe_date_id_idx')],
            },
        ),
    ]
