# Generated by Django 5.2.4 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_periodepaie_employe_actif_employe_frequence_paie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresTauxPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_effet', models.DateField()),
                ('date_fin_effet', models.DateField(blank=True, null=True)),
                ('taux_rrq_employe', models.DecimalField(decimal_places=5, max_digits=7)),
                ('taux_rrq_employeur', models.DecimalField(decimal_places=5, max_digits=7)),
                ('max_assurable_rrq', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_rqap_employe', models.DecimalField(decimal_places=5, max_digits=7)),
                ('taux_rqap_employeur', models.DecimalField(decimal_places=5, max_digits=7)),
                ('max_assurable_rqap', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_ae_employe', models.DecimalField(decimal_places=5, max_digits=7)),
                ('taux_ae_employeur', models.DecimalField(decimal_places=5, max_digits=7)),
                ('max_assurable_ae', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_fss_employeur', models.DecimalField(decimal_places=5, max_digits=7)),
                ('taux_csst_employeur', models.DecimalField(decimal_places=5, max_digits=7)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parametres de taux de paie',
                'verbose_name_plural': 'Parametres de taux de paie',
                'ordering': ['-date_debut_effet', '-id'],
            },
        ),
    ]
