# Generated by Django 6.0.7 on 2026-08-11 02:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0004_paie_heures_supp'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_rrq_premiere_cotisation_supplementaire_employe',
            field=models.DecimalField(decimal_places=5, default=Decimal('1.00000'), max_digits=7),
        ),
    ]
