# Generated by Django 6.0.7 on 2026-08-11 23:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0005_parametrestauxpaie_taux_rrq_premiere_cotisation_supplementaire_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='paie',
            name='gains_assurables_ae',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paie',
            name='gains_ouvrant_droit_rrq',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='FeuilletFiscalAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('t4_revenu_emploi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('t4_cotisation_rrq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('t4_cotisation_ae', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('t4_impot_federal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('t4_gains_assurables_ae', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('t4_gains_ouvrant_droit_rrq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rl1_revenu_emploi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rl1_cotisation_rrq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rl1_cotisation_rqap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rl1_impot_quebec', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feuillets_fiscaux', to='paie.employe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employe', 'annee'), name='feuillet_unique_employe_annee')],
            },
        ),
    ]
