# Generated by Django 6.0.7 on 2026-08-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0006_paie_gains_assurables_ae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='adresse_postale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='nas',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
