# Generated by Django 6.0.6 on 2026-07-07 00:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0010_parametrestauxpaie_rrq_regime_supplementaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='abattement_federal_quebec',
            field=models.DecimalField(decimal_places=5, default=Decimal('16.50000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='credit_personnel_federal_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('16452.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='credit_personnel_quebec_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('18952.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='deduction_travailleur_qc_max_annuelle',
            field=models.DecimalField(decimal_places=2, default=Decimal('1450.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='montant_canadien_pour_emploi',
            field=models.DecimalField(decimal_places=2, default=Decimal('1501.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='seuil_federal_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('58523.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='seuil_federal_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('117045.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='seuil_federal_3',
            field=models.DecimalField(decimal_places=2, default=Decimal('181440.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='seuil_federal_4',
            field=models.DecimalField(decimal_places=2, default=Decimal('258482.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='seuil_qc_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('54345.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='seuil_qc_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('108680.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='seuil_qc_3',
            field=models.DecimalField(decimal_places=2, default=Decimal('132245.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_credit_federal',
            field=models.DecimalField(decimal_places=5, default=Decimal('14.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_credit_quebec',
            field=models.DecimalField(decimal_places=5, default=Decimal('14.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_federal_1',
            field=models.DecimalField(decimal_places=5, default=Decimal('14.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_federal_2',
            field=models.DecimalField(decimal_places=5, default=Decimal('20.50000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_federal_3',
            field=models.DecimalField(decimal_places=5, default=Decimal('26.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_federal_4',
            field=models.DecimalField(decimal_places=5, default=Decimal('29.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_federal_5',
            field=models.DecimalField(decimal_places=5, default=Decimal('33.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_qc_1',
            field=models.DecimalField(decimal_places=5, default=Decimal('14.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_qc_2',
            field=models.DecimalField(decimal_places=5, default=Decimal('19.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_qc_3',
            field=models.DecimalField(decimal_places=5, default=Decimal('24.00000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_qc_4',
            field=models.DecimalField(decimal_places=5, default=Decimal('25.75000'), max_digits=7),
        ),
    ]
