# Generated by Django 6.0.7 on 2026-08-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0010_vue_paie_journal_lignes_employeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrestauxpaie',
            name='taux_cnt_employeur',
        ),
    ]
