# Generated by Django 6.0.7 on 2026-08-14 03:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0011_remove_parametrestauxpaie_taux_cnt_employeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='constante_qc_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='constante_qc_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='constante_qc_3',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='constante_qc_4',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
