# Generated by Django 6.0.7 on 2026-08-14 13:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0012_parametrestauxpaie_constante_qc_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='max_ae_credit_federal_qc',
            field=models.DecimalField(decimal_places=2, default=Decimal('895.70'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='max_base_credit_rrq_federal',
            field=models.DecimalField(decimal_places=2, default=Decimal('3768.30'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='max_rqap_credit_federal',
            field=models.DecimalField(decimal_places=2, default=Decimal('442.90'), max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrestauxpaie',
            name='taux_rqap_credit_federal',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.43000'), max_digits=7),
        ),
    ]
