# Generated by Django 6.0.7 on 2026-08-26 14:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0014_paiejournalligne_date_paie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeVacancesDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_vacances_depart', to='paie.employe')),
            ],
            options={
                'verbose_name': 'Solde de départ vacances',
                'verbose_name_plural': 'Soldes de départ vacances',
            },
        ),
    ]
