# Generated by Django 6.0.6 on 2026-06-21 19:26

import compte.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('no_total', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999), compte.models.validate_4_digits])),
                ('desc', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Total',
                'verbose_name_plural': 'Totaux',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999), compte.models.validate_4_digits])),
                ('libelle', models.CharField(max_length=30)),
                ('no_total', models.ForeignKey(db_column='no_total', on_delete=django.db.models.deletion.CASCADE, to='compte.total', verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
            },
        ),
    ]
