# Generated by Django 6.0.7 on 2026-07-27 16:24

import compte.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999), compte.models.validate_4_digits])),
                ('libelle', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('no_total', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999), compte.models.validate_total_number])),
                ('desc', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Total',
                'verbose_name_plural': 'Totaux',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('logo', models.CharField(default='images.png', help_text='Nom du fichier logo dans static/images/logos (ex: images.png).', max_length=100)),
                ('adresse', models.CharField(max_length=60)),
                ('ville', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=60)),
                ('pays', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fin_annee_jour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name="Jour de fin d'exercice")),
                ('fin_annee_mois', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name="Mois de fin d'exercice")),
                ('taxes_mode', models.CharField(choices=[('RECLAMER', 'Les taxes sont generalement a reclamer'), ('PAYER', 'Les taxes sont generalement a payer')], default='RECLAMER', max_length=16)),
                ('date_debut_periode_paie_annee', models.DateField(blank=True, null=True, verbose_name='Date de debut de la premiere periode de l annee')),
                ('date_premier_paiement_paie_annee', models.DateField(blank=True, null=True, verbose_name='Date du premier paiement de l annee')),
                ('taux_cnesst_employeur', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True, verbose_name='Taux CNESST employeur')),
                ('taux_fss_employeur', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True, verbose_name='Taux FSS employeur')),
                ('comptes_paie_autres', models.JSONField(blank=True, default=list, help_text='Liste optionnelle de numeros de comptes supplementaires pour la paie.')),
                ('cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_cap', to='compte.compte')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_car', to='compte.compte')),
                ('compte_benefices_marginaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_benefices_marginaux', to='compte.compte')),
                ('compte_das_federales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_das_federales', to='compte.compte')),
                ('compte_das_provinciales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_das_provinciales', to='compte.compte')),
                ('compte_fr_retard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_fr_retard', to='compte.compte')),
                ('compte_salaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_salaire', to='compte.compte')),
                ('compte_salaires_a_payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_salaires_a_payer', to='compte.compte')),
                ('compte_tps_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_tps_payee', to='compte.compte')),
                ('compte_tps_percue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_tps_percue', to='compte.compte')),
                ('compte_tvq_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_tvq_payee', to='compte.compte')),
                ('compte_tvq_percue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_tvq_percue', to='compte.compte')),
                ('compte_vacances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_vacances', to='compte.compte')),
                ('compte_vacances_a_payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_vacances_a_payer', to='compte.compte')),
                ('frequence_paie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='paie.frequencepaie', verbose_name='Fréquence de paie')),
            ],
        ),
        migrations.CreateModel(
            name='SoldeAuxLivres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_depart', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_aux_livres', to='compte.compte')),
            ],
            options={
                'verbose_name': 'Solde aux livres',
                'verbose_name_plural': 'Soldes aux livres',
                'ordering': ['compte__numero'],
            },
        ),
        migrations.AddField(
            model_name='compte',
            name='no_total',
            field=models.ForeignKey(db_column='no_total', on_delete=django.db.models.deletion.CASCADE, to='compte.total', verbose_name='Total'),
        ),
    ]
