# Generated by Django 6.0.6 on 2026-06-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeAuxLivres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_depart', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_aux_livres', to='compte.compte')),
            ],
            options={
                'verbose_name': 'Solde aux livres',
                'verbose_name_plural': 'Soldes aux livres',
                'ordering': ['compte__numero'],
            },
        ),
    ]
