# Generated by Django 6.0.7 on 2026-08-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='numero_entreprise_federal',
            field=models.CharField(blank=True, help_text="Numéro d'entreprise attribué par l'ARC (ex: 123456789RP0001).", max_length=15, null=True, verbose_name="Numéro d'entreprise (NE) fédéral"),
        ),
        migrations.AddField(
            model_name='setting',
            name='numero_identification_quebec',
            field=models.CharField(blank=True, help_text="Numéro d'identification, dossier de retenues à la source (ex: 1234567890RS0001).", max_length=20, null=True, verbose_name="Numéro d'identification Revenu Québec"),
        ),
    ]
