# Generated by Django 6.0.6 on 2026-06-28 23:18

import compte.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_soldeauxlivres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='no_total',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999), compte.models.validate_total_number]),
        ),
    ]
