# Generated by Django 6.0.7 on 2026-08-16 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_setting_numero_entreprise_federal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='compte_cheques',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_compte_cheques', to='compte.compte'),
        ),
    ]
