# Generated by Django 6.0.6 on 2026-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_delete_bulletinpaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='date_debut_periode_paie_annee',
            field=models.DateField(blank=True, null=True, verbose_name='Date de debut de la premiere periode de l annee'),
        ),
        migrations.AddField(
            model_name='setting',
            name='date_premier_paiement_paie_annee',
            field=models.DateField(blank=True, null=True, verbose_name='Date du premier paiement de l annee'),
        ),
    ]
