# Generated by Django 6.0.7 on 2026-08-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_setting_compte_cheques'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='no_cheque_depart',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
