# Generated by Django 6.0.6 on 2026-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_alter_total_no_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='libelle',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='total',
            name='desc',
            field=models.CharField(max_length=120),
        ),
    ]
