# Generated by Django 6.0.7 on 2026-08-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_setting_no_cheque_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_ouvert', models.BooleanField(default=True)),
                ('cloture_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exercice financier',
                'verbose_name_plural': 'Exercices financiers',
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('est_ouvert', True)), fields=('est_ouvert',), name='un_seul_exercice_ouvert_a_la_fois')],
            },
        ),
    ]
