# Generated by Django 6.0.7 on 2026-08-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_exercicefinancier'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='compte_bnr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_bnr', to='compte.compte', verbose_name='Compte Bénéfices non répartis'),
        ),
    ]
