# Generated by Django 6.0.7 on 2026-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_setting_compte_bnr'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercicefinancier',
            name='un_seul_exercice_ouvert_a_la_fois',
        ),
        migrations.AddField(
            model_name='exercicefinancier',
            name='est_audite',
            field=models.BooleanField(default=False, help_text="Coché une fois l'audit accepté et signé — l'exercice est alors clos officiellement.", verbose_name='Audité et signé'),
        ),
        migrations.RemoveField(
            model_name='exercicefinancier',
            name='est_ouvert',
        ),
    ]
