# Generated by Django 6.0.6 on 2026-08-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_remove_exercicefinancier_un_seul_exercice_ouvert_a_la_fois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='taxes_mode',
            field=models.CharField(choices=[('RECLAMER', 'Les taxes sont generalement a reclamer'), ('PAYER', 'Les taxes sont generalement a payer'), ('AUCUN', "Ni l'un ni l'autre (cas rare)")], default='RECLAMER', max_length=16),
        ),
    ]
