# Generated by Django 6.0.7 on 2026-08-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0008_setting_taxes_mode_ajout_aucun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='taxes_mode',
            field=models.CharField(choices=[('RECLAMER', 'Les taxes sont generalement a reclamer'), ('PAYER', 'Les taxes sont generalement a payer'), ('AUCUN', "Ni l'un ni l'autre")], default='RECLAMER', max_length=16),
        ),
    ]
